version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: chet
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example
    ports:
      - 5432:5432
